//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bitirmePro.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class uni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uni()
        {
            this.yorumIicerik = new HashSet<yorumIicerik>();
        }
    
        public int uniID { get; set; }
        public string uniGBASLIK { get; set; }
        public string uniICERIK { get; set; }
        public Nullable<System.DateTime> uniTARIH { get; set; }
        public string uniGORSEL { get; set; }
        public Nullable<byte> uniTUR { get; set; }
        public Nullable<byte> uniKATEGORI { get; set; }
        public Nullable<byte> uniBolum { get; set; }
    
        public virtual kategori kategori { get; set; }
        public virtual tur tur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yorumIicerik> yorumIicerik { get; set; }
        public virtual bolum bolum { get; set; }
    }
}
